name: Terramate

on:
  workflow_dispatch:
    inputs:
      terraform:
        description: 'Terraform Operation'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      environment:
        description: 'Environment to run tests against'
        default: 'production'
        type: environment
        options:
        - production
        - staging
        - development
        - sandbox

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897722666736:role/NC-Github-Federated
          aws-region: us-east-2

      - name: Run AWS CLI command
        run: aws sts get-caller-identity

      - name: Set up Go (required for Terramate)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      # - name: Install Terramate
      #   uses: terramate-io/terramate-action@v2

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.1
          terraform_wrapper: false
          
      - name: Install Terramate
        run: |
          go install github.com/terramate-io/terramate/cmd/terramate@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Verify Terramate installation
        run: terramate --version

      - name: Run Terramate
        run: |
          terramate generate
          terramate run -- terraform init
          terramate run -- terraform plan

      - name: Terraform Apply
        if: inputs.terraform == 'apply'
        run: terramate run --terraform apply -auto-approve -input=false
