name: Deploy to AWS

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::897722666736:role/NC-Github-Federated
          aws-region: us-east-2

      - name: Run AWS CLI command
        run: aws sts get-caller-identity

      - name: Set up Go (required for Terramate)
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Install Terramate
        run: |
          go install github.com/terramate-io/terramate/cmd/terramate@latest
          echo "$HOME/go/bin" >> $GITHUB_PATH

      - name: Verify Terramate installation
        run: terramate --version

      - name: Run Terramate
        run: |
          terramate generate
          terramate run -- terraform init
          terramate run -- terraform plan
